# Generated by Django 4.0 on 2022-01-02 13:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0013_alter_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('username', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=80, null=True, unique=True)),
                ('head_line', models.CharField(blank=True, max_length=200, null=True)),
                ('Bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to='profiles/')),
                ('resume_link', models.CharField(blank=True, max_length=200, null=True)),
                ('insta_link', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(to='blog.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
