# Generated by Django 4.0 on 2021-12-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_category_state_article_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='state',
            field=models.IntegerField(choices=[{0, 'disable'}, {1, 'enable'}], default=0),
        ),
    ]
