# Generated by Django 4.0 on 2021-12-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='deleted',
            field=models.IntegerField(choices=[{0, 'disable'}, {'enable', 1}], default=0),
        ),
    ]
