# Generated by Django 4.0 on 2021-12-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
