# Generated by Django 4.0 on 2022-01-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_article_slug'),
        ('portfolio', '0002_project_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
